# Generated by Django 5.1.3 on 2025-08-28 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CleanupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('users_deleted', models.IntegerField()),
                ('active_users_remaining', models.IntegerField()),
            ],
            options={
                'db_table': 'cleanup_report',
                'managed': True,
            },
        ),
    ]
